###

# curl --header "Content-Type: application/json"
#  --request POST
#  --data '{"username":"xyz","password":"xyz"}'
#  http://localhost:3000/api/login
POST http://localhost:5000/events
Content-Type: application/json

{
  "operation": "email_send2",
  "description" : "email about new account for user : u94842"
}


###
GET http://localhost:9090/events/gdghgfd

###
GET http://localhost:9090/events
