###

# curl --header "Content-Type: application/json"
#  --request POST
#  --data '{"username":"xyz","password":"xyz"}'
#  http://localhost:3000/api/login
POST http://localhost:9090/events
Content-Type: application/json

{
  "operation": "op1212",
  "description" : "services testing for simple test"
}


###
GET http://localhost:9090/events/gdghgfd

###
GET http://localhost:9090/events
